Add Bryan's details
AY2425S1-CS2103T-T08-2/tp pull request #72
Opened 2024-09-30 06:29 UTC by bryancheny

Closes #71

2024-09-30 07:06 UTC, dwsc37 approved these changes
LGTM, but hold on merging for now

2024-10-01 15:30 UTC, dwsc37 commented on docs/AboutUs.md
> +* Responsibilities: Documentation + Testing
I have updated it

2024-10-02 04:08 UTC, dwsc37 requested changes
Just need to add back the photo

2024-10-02 12:22 UTC, dwsc37 approved these changes
LGTM

2024-10-02 12:24 UTC, audipras approved these changes

2024-10-02 12:24 UTC, merged